services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${APP_PORT:-80}:80'
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_URL: 'http://localhost'
      DB_CONNECTION: pgsql
      DB_HOST: pgsql
      DB_PORT: 5432
      DB_DATABASE: '${DB_DATABASE}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD:-secret}'
    depends_on:
      - pgsql

  pgsql:
    image: 'postgres:16-alpine'
    ports:
      - '${FORWARD_DB_PORT:-5433}:5432'
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'sail-pgsql:/var/lib/postgresql/data'

volumes:
  sail-pgsql:
    driver: local
